---
- hosts: webservers
  become: yes

  tasks:

    - name: Stop Existing App
      shell: pkill -f 'java -jar'
      ignore_errors: yes

    - name: Create App Directory
      file:
        path: /opt/springboot
        state: directory

    - name: Copy JAR File
      copy:
        src: /var/lib/jenkins/workspace/GitOps/target/academic-result-platform-0.0.1-SNAPSHOT.jar
        dest: /opt/springboot/app.jar

    - name: Start Spring Boot App
      shell: |
        nohup java -jar /opt/springboot/app.jar > /opt/springboot/app.log 2>&1 &