---
- hosts: webservers
  become: yes

  tasks:

    - name: Stop Existing App
      shell: pkill -f "java -jar" || true
      failed_when: false
      changed_when: false

    - name: Create App Directory
      file:
        path: /opt/springboot
        state: directory

    - name: Copy JAR File
      copy:
        src: "{{ lookup('pipe', 'find /var/lib/jenkins/workspace -name \"*.jar\" | grep SNAPSHOT.jar | head -1') }}"
        dest: /opt/springboot/app.jar

    - name: Start Spring Boot App
      shell: |
        nohup java -jar /opt/springboot/app.jar > /opt/springboot/app.log 2>&1 &